" Generated by vim-plug
" Sat 11 Jun 2022 12:40:46 PM CST
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['bufferline.nvim'].commit = 'de66766716ab29414c7dd078d16b4773ab53a0bd'
silent! let g:plugs['coc.nvim'].commit = '042d0c7d0f3a29409347fe5c2b754f6686f16578'
silent! let g:plugs['dracula'].commit = 'd7723a842a6cfa2f62cf85530ab66eb418521dc2'
silent! let g:plugs['fzf'].commit = '3b7a962dc6db227d18faecb25c793431ce7e8640'
silent! let g:plugs['fzf.vim'].commit = 'd5f1f8641b24c0fd5b10a299824362a2a1b20ae0'
silent! let g:plugs['galaxyline.nvim'].commit = 'b12853a488ec8921eac9161c93f61a340102d502'
silent! let g:plugs['indent-blankline.nvim'].commit = '6177a59552e35dfb69e1493fd68194e673dc3ee2'
silent! let g:plugs['nvim-colorizer.lua'].commit = '36c610a9717cc9ec426a07c8e6bf3b3abcb139d6'
silent! let g:plugs['nvim-tree.lua'].commit = '84cb79e760964820391bd5e66579e1bdb36f1103'
silent! let g:plugs['nvim-web-devicons'].commit = '8a3ab5eb181b5a10d6ed031f3eeafa1acd2058f9'
silent! let g:plugs['onehalf'].commit = '141c775ace6b71992305f144a8ab68e9a8ca4a25'
silent! let g:plugs['rust.vim'].commit = '4aa69b84c8a58fcec6b6dad6fe244b916b1cf830'
silent! let g:plugs['syntastic'].commit = 'b7f4f71539038d33f173bfa72631737da049575a'
silent! let g:plugs['vim-js'].commit = '90f340d31907590fad059cd9aab03a55ab49e352'

PlugUpdate!

